### ISSUE TITLE
API Key exposed 

### ISSUE THREAD

**Issue by suvadityamuk** [arafaysaleem/covid_tracker#13]
API keys exposed in covid-tracker-master/lib/network-requests/api_service.dart. Please check and rectify.

**Comment by arafaysaleem** [comment]
Thanks for pointing it out. I made this project as a beginner and never took care of this thing. I'll convert it into an environment variable right away.

**Comment by suvadityamuk** [comment]
Also, just saying. Might wanna check this out [here](https://github.com/zaidmukaddam/Covid-19-Tracker "Folium Documentation")

**Comment by arafaysaleem** [comment]
Since the project was open sourced with the intent of allowing people to take inspiration, it's fine if someone clones it. The licensing was quite open.

**Comment by suvadityamuk** [comment]
Sure, just letting you know. But, the license was deleted, which was in contravention to the license rules itself. That's all.
